### ISSUE TITLE
WTF la page

### ISSUE THREAD

**Issue by romch007** [Moll-Florent/EvaLauncher-WebSite#5]
Mec fais gaffe la page est vraiment horrible, quelques règles :
- N'utilise __jamais__ de `<table>` pour organiser (à part pour le menu du haut) c'est hyper déconseillé.
- Ne met pas de style dans les balises c'est illisible, fais un fichier `style.css` que tu importes.
- Fais du ménage il y a plein de balises vide et d'attributs inutiles
- Évite le copier-coller depuis d'autre page
- Pour récupérer et envoyer sur GitHub utilise [git](https://rogerdudler.github.io/git-guide/index.fr.html) sinon tu vas galérer

Regarde des tutos css [ici](https://www.w3schools.com/css/) ça va vraiment t'aider.

Aller bonne chance et si tu veux je peut d'aider je me fais un peu chier.

**Comment by Moll-Florent** [comment]
> Mec fais gaffe la page est vraiment horrible, quelques règles :
> 
> * N'utilise **jamais** de `<table>` pour organiser (à part pour le menu du haut) c'est hyper déconseillé.
> * Ne met pas de style dans les balises c'est illisible, fais un fichier `style.css` que tu importes.
> * Fais du ménage il y a plein de balises vide et d'attributs inutiles
> * Évite le copier-coller depuis d'autre page
> * Pour récupérer et envoyer sur GitHub utilise [git](https://rogerdudler.github.io/git-guide/index.fr.html) sinon tu vas galérer
> 
> Regarde des tutos css [ici](https://www.w3schools.com/css/) ça va vraiment t'aider.
> 
> Aller bonne chance et si tu veux je peut d'aider je me fais un peu chier.

**Comment by Moll-Florent** [comment]
@romch007 OK merci 🙂
